#if !defined(__4245487EF026C4FE6C1ABBBB978__)
# define __4245487EF026C4FE6C1ABBBB978__

# include <xpadf/common/macros.h>
# include <xpadf/common/types.h>

# define XPADF_OK 0x000000000

# define XPADF_DEBUG_MASK       0x010000000
# define XPADF_INFORMATION_MASK 0x020000000
# define XPADF_WARNING_MASK     0x040000000
# define XPADF_ERROR_MASK       0x080000000

# define XPADF_SUCCEEDED(__exp__) (XPADF_WARNING_MASK > (__exp__))
# define XPADF_FAILED(__exp__)    (XPADF_WARNING_MASK < (__exp__))

# define XPADF_CHECK_STATUS(__mask__, __exp__) (__mask__ & (__exp__))

# define XPADF_IS_DEBUG(__exp__)       XPADF_CHECK_STATUS(XPADF_DEBUG_MASK,       __exp__)
# define XPADF_IS_INFORMATION(__exp__) XPADF_CHECK_STATUS(XPADF_INFORMATION_MASK, __exp__)
# define XPADF_IS_WARNING(__exp__)     XPADF_CHECK_STATUS(XPADF_WARNING_MASK,     __exp__)
# define XPADF_IS_ERROR(__exp__)       XPADF_CHECK_STATUS(XPADF_ERROR_MASK,       __exp__)

# define XPADF_CONVERT_ERROR_TO_WARNING(__status__) (((__status__) & ~XPADF_ERROR_MASK) | XPADF_WARNING_MASK)

# define XPADF_GLOBAL_MODULE 0x00000

# define XPADF_DEFINE_STATUS_CODE(__mask__, __module__, __code__) (__mask__ | ((__module__ & 0x00fff) << 16) | (__code__ & 0x0ffff))

# if !defined(XPADF_DEFINE_STATUS)
#  define XPADF_DEFINE_STATUS(__name__, __module__, __code__)           \
  extern CXPADF_RESULT XPADF_DEBUG_##__name__;                          \
  extern CXPADF_RESULT XPADF_INFORMATION_##__name__;                    \
  extern CXPADF_RESULT XPADF_WARNING_##__name__;                        \
  extern CXPADF_RESULT XPADF_ERROR_##__name__;
# endif /* !XPADF_DEFINE_STATUS */
  
XPADF_DEFINE_STATUS(INVALID_PARAMETERS,          XPADF_GLOBAL_MODULE, 0x000000001)
XPADF_DEFINE_STATUS(OUT_OF_MEMORY,               XPADF_GLOBAL_MODULE, 0x000000002)
XPADF_DEFINE_STATUS(CREATE_LOCK,                 XPADF_GLOBAL_MODULE, 0x000000003)
XPADF_DEFINE_STATUS(INITIALIZE_THREAD_ATTRIBUTE, XPADF_GLOBAL_MODULE, 0x000000004)
XPADF_DEFINE_STATUS(SET_THREAD_ATTRIBUTE,        XPADF_GLOBAL_MODULE, 0x000000005)
XPADF_DEFINE_STATUS(CREATE_THREAD,               XPADF_GLOBAL_MODULE, 0x000000006)
XPADF_DEFINE_STATUS(INVALID_OPERATION,           XPADF_GLOBAL_MODULE, 0x000000007)
XPADF_DEFINE_STATUS(CREATE_SEMAPHORE,            XPADF_GLOBAL_MODULE, 0x000000008)
XPADF_DEFINE_STATUS(DRAINING,                    XPADF_GLOBAL_MODULE, 0x000000009)
XPADF_DEFINE_STATUS(OPEN_DEVICE,                 XPADF_GLOBAL_MODULE, 0x00000000a)
XPADF_DEFINE_STATUS(REGISTER_IO,                 XPADF_GLOBAL_MODULE, 0x00000000b)
XPADF_DEFINE_STATUS(POLL_IO,                     XPADF_GLOBAL_MODULE, 0x00000000c)

#endif /* !__4245487EF026C4FE6C1ABBBB978__ */
