#if !defined(__B29C61555BA01ABD1495EDA4746__)
# define __B29C61555BA01ABD1495EDA4746__

# include <xpadf/common/macros.h>

# if defined(__GNUC__)
#  include <xpadf/common/gcc/types.h>
# endif /* Compiler Type */

XPADF_DEFINE_DATA_TYPE(long int,          XPADF_LONG );
XPADF_DEFINE_DATA_TYPE(unsigned long int, XPADF_ULONG);

XPADF_DEFINE_DATA_TYPE(XPADF_UINT32, XPADF_RESULT);
XPADF_DEFINE_DATA_TYPE(XPADF_ULONG,  XPADF_SIZE  );
XPADF_DEFINE_DATA_TYPE(XPADF_UINT64, XPADF_SIZE64);
XPADF_DEFINE_DATA_TYPE(XPADF_UINT16, XPADF_PORT  );
XPADF_DEFINE_DATA_TYPE(XPADF_UINT8,  XPADF_BYTE  );

typedef void *PXPADF_VOID;
XPADF_DEFINE_DATA_TYPE(PXPADF_VOID, XPADF_PVOID);

enum XPADF_BOOL {XPADF_FALSE = 0, XPADF_TRUE = 1};
XPADF_DECLARE_ENUM(XPADF_BOOL);

XPADF_DECLARE_STRUCT(XPADF_BUFFER);
XPADF_DECLARE_STRUCT(XPADF_BUFFER64);

struct XPADF_BUFFER {
  XPADF_PVOID m_pBuffer;
  XPADF_SIZE  m_nSize;
  XPADF_SIZE  m_nCapacity;
};

struct XPADF_BUFFER64 {
  XPADF_PVOID  m_pBuffer;
  XPADF_SIZE64 m_nSize;
  XPADF_SIZE64 m_nCapacity;
};

#endif /* !__B29C61555BA01ABD1495EDA4746__ */
